# Generated by Django 2.0.2 on 2018-02-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Windowmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('temparature', models.TextField()),
                ('moisture', models.TextField()),
                ('finedust', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
