# Generated by Django 2.0.2 on 2018-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='finedust_siheung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('time', models.TextField()),
                ('pm10', models.TextField()),
                ('pm25', models.TextField()),
                ('pm10value', models.TextField()),
                ('pm25value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Weathermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('weather', models.TextField()),
                ('temp', models.TextField()),
                ('mintemp', models.TextField()),
                ('maxtemp', models.TextField()),
                ('hudmity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Windowmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.TextField()),
                ('humidity', models.TextField()),
                ('finedust', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
